---

- name: "Setup R80 Policy"
  hosts:  "{{ mgmt_server }}"
  connection: httpapi
  gather_facts: no
  vars_files: chkp_vars.yml
  roles:
     - role: R80_Policy 

       #- name: "Install Policy"
       #  hosts:  "{{ mgmt_server }}"
       # connection: httpapi
       #gather_facts: no
       #vars_files: chkp_vars.yml
       # roles:
       #- role: CHKP_Install_Policy 
